# Generated by Django 5.1.5 on 2025-01-30 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WeatherData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(max_length=100)),
                ("temperature", models.FloatField()),
                ("humidity", models.IntegerField()),
                ("wind_speed", models.FloatField()),
                ("description", models.CharField(max_length=255)),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
